### ISSUE TITLE
Al instalar el modulo no me permite configurar el res.company

### ISSUE THREAD

**Issue by morrillo** [ctmil/meli_oerp#1]
Da el siguiente error:

Traceback (most recent call last):
  File "/home/gustavo/odoo/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/gustavo/odoo/openerp/http.py", line 517, in dispatch
    result = self._call_function(*_self.params)
  File "/home/gustavo/odoo/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/gustavo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/gustavo/odoo/openerp/http.py", line 280, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/gustavo/odoo/openerp/http.py", line 733, in __call__
    return self.method(_args, *_kw)
  File "/home/gustavo/odoo/openerp/http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "/home/gustavo/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/gustavo/odoo/addons/web/controllers/main.py", line 927, in _call_kw
    records = getattr(request.session.model(model), method)(_args, *_kwargs)
  File "/home/gustavo/odoo/openerp/http.py", line 835, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/home/gustavo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/gustavo/odoo/openerp/models.py", line 3109, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/gustavo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/gustavo/odoo/openerp/models.py", line 3141, in read
    self._read_from_database(stored)
  File "/home/gustavo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/gustavo/odoo/openerp/models.py", line 3303, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/gustavo/odoo/openerp/osv/fields.py", line 1308, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/gustavo/odoo/addons/meli_oerp/company.py", line 56, in get_meli_state
    response = meli.get("/items/")
  File "/home/gustavo/odoo/addons/meli_oerp/melisdk/meli.py", line 81, in get
    response = requests.get(uri, params=urlencode(params), headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='api.mercadolibre.com', port=443): Max retries exceeded with url: /items/ (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)

**Comment by morrillo** [comment]
X
