### ISSUE TITLE
FileNotFoundError: File not found: meli_oerp/views/atrributes_view.xml

### ISSUE THREAD

**Issue by nahuuss** [ctmil/meli_oerp#101]
Estimados,

Realice la primer instalacion en un demo sin problemas en Odoo15, al realizar la instalacion en una version de Odoo16 me devuelve el error citado. Al realizar nuevamente una instalacion en Odoo15 e instalar el Addon en una instalación limpia sin nada modificado me devuelve el mismo error que en Odoo16. Podrian indicarme porque me pide el archivo atrributes_view.xml en view?

Gracias!!

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 1587, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo/odoo/http.py", line 1614, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/odoo/http.py", line 1811, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/odoo/http.py", line 700, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/opt/odoo/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 487, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 757, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/opt/odoo/odoo/odoo/tools/misc.py", line 203, in file_open
    path = file_path(name, filter_ext=filter_ext)
  File "/opt/odoo/odoo/odoo/tools/misc.py", line 184, in file_path
    raise FileNotFoundError("File not found: " + file_path)
FileNotFoundError: File not found: meli_oerp/views/atrributes_view.xml

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://xxxx.xxxx.com.ar/web/assets/736-cf65eb6/web.assets_backend.min.js:970:163)
    at XMLHttpRequest.<anonymous> (https://xxxx.xxxx.com.ar/web/assets/736-cf65eb6/web.assets_backend.min.js:978:13)

**Comment by dmy1983** [comment]
Hola , estoy con el mismo problema, descubriste algo?

**Comment by nahuuss** [comment]
> Hola , estoy con el mismo problema, descubriste algo?

Si, usa la version del 13 de marzo en el repositorio, hasta esa fecha no se realizo el cambio que da este mensaje.

https://github.com/ctmil/meli_oerp/tree/add20ad42af53e4aa0c2782329a10b648a2e0baa
