### ISSUE TITLE
Active Issues in Odoo 17

### ISSUE THREAD

**Issue by AR-Mate** [ctmil/meli_oerp#116]
When I want to activate the module in my local odoo I get the following error:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1765, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1792, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1996, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 590, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 192, in load_module_graph
    getattr(py_module, pre_init)(env)
  File "/usr/lib/python3/dist-packages/odoo/addons/meli_oerp/__init__.py", line 33, in pre_init_hook
    env = api.Environment(cr, SUPERUSER_ID, {})
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 511, in __new__
    assert isinstance(cr, BaseCursor)
AssertionError

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@http://localhost:8069/web/assets/debug/web.assets_web.js:27764:9 (/web/static/src/core/network/rpc_service.js:11)
    makeErrorFromResponse@http://localhost:8069/web/assets/debug/web.assets_web.js:27790:19 (/web/static/src/core/network/rpc_service.js:37)
    jsonrpc/promise</<@http://localhost:8069/web/assets/debug/web.assets_web.js:27838:48 (/web/static/src/core/network/rpc_service.js:85)

In odoo 16 I was able to install it without a problem but when doing it in 17 I get that error, can someone pass it on to me or did the same thing happen to me?

**Comment by AR-Mate** [comment]
buenas, el error sigue estando, creo que se debe mas a lo ultimo que aparece en la cadena de error 
"File "/usr/lib/python3/dist-packages/odoo/api.py", line 511, in __new__
    assert isinstance(cr, BaseCursor)
AssertionError"
tiene que ver con esa sentencia con odoo 17, con odoo 16 no correr ningun problema, al hacer lo mismo en odoo 17 con la version de meli de 17 larga ese error que te mencione antes donde lo ultimo dice de ese error de instancia, yo al odoo lo tengo instalado en ubuntu 22.04 por las dudas

![imagen_2024-03-14_152233131](https://github.com/ctmil/meli_oerp/assets/144135834/7954b0c9-39e7-4fd7-b16f-f379044dafda)
