### ISSUE TITLE
Error when product have more them One image

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [ctmil/meli_oerp#25]
this error occur only product have more then one image:

Traceback (most recent call last):
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "w:\odoo\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "W:\Odoo\_Dados\addons\11.0\web_syncer\http.py", line 9, in __call__
    result = self.method(*args, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "w:\odoo\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "W:\Odoo\_Dados\addons\11.0\meli_oerp\models\product_post.py", line 159, in product_post
    res = product.product_post()
  File "W:\Odoo\_Dados\addons\11.0\meli_oerp\models\product.py", line 850, in product_post
    multi_images_ids = product.product_meli_upload_multi_images()
  File "W:\Odoo\_Dados\addons\11.0\meli_oerp\models\product.py", line 567, in product_meli_upload_multi_images
    _logger.info( "meli upload:" + response.content )
TypeError: must be str, not bytes

Any suggestion/idea?
I willl styll trying to resolver this, but all help will become!
thanks a lot!

**Comment by Alexandre-Bernardes** [comment]
I make it work!
I comment the line #567 with error, but obviously, this is not the recommended!

**Comment by morrillo** [comment]
I bet you did, I did not get to the office yet but I was about to tell the developer about this bug (actually it happens when it logs to the log file, it should log when the content is not binary)
where are you from? just curious...

**Comment by Alexandre-Bernardes** [comment]
I'm in Rio de Janeiro/Brazil, and you?
(nice to meet you)

**Comment by Capriatto** [comment]
i got the same issue, would you recommend to comment the line that Alexandre suggested? @morrillo
