### ISSUE TITLE
El campo mercadolibre_import_search_sku no existe - v.11.0.20.24 v11 ce

### ISSUE THREAD

**Issue by martinllanos** [ctmil/meli_oerp#41]
**Error:** El campo `mercadolibre_import_search_sku` no existe. No permite instalar el módulo.
**Version Odoo:** Odoo 11 CE
**Version del modulo:** 11.0.20.24
**Coomit:** e3362fc8

`Contexto del error:
Vista `res.company.form.meli`
[view_id: 1772, xml_id: n/a, model: res.company, parent_id: 95]
2020-07-29 19:13:18,669 15796 WARNING prod_sequana_control_v6 odoo.modules.loading: Transient module states were reset
2020-07-29 19:13:18,671 15796 ERROR prod_sequana_control_v6 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/sequana11/server/odoo/odoo/models.py", line 1057, in _validate_fields
    check(self)
  File "/home/sequana11/server/odoo/odoo/addons/base/ir/ir_ui_view.py", line 342, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/home/sequana11/server/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1083, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/home/sequana11/server/odoo/odoo/addons/base/ir/ir_ui_view.py", line 533, in raise_view_error
    raise ValueError(message)
ValueError: El campo `mercadolibre_import_search_sku` no existe
`

**Comment by martinllanos** [comment]
Era un problema que arrastraba en el template.
