### ISSUE TITLE
[12.0] Error al traer orden

### ISSUE THREAD

**Issue by FedericoLaTorre** [ctmil/meli_oerp#42]
El error se produce en una orden con carrito de compras (múltiples productos) con 5 productos.

ERROR: insert or update on table "mercadolibre_order_items" violates foreign key constraint "mercadolibre_order_items_product_id_fkey"
DETAIL:  Key (product_id)=(1552) is not present in table "product_product".
 
2020-09-21 00:53:23,508 27002 INFO XXXX odoo.addons.meli_oerp.models.orders: orders_query_iterate > Error actualizando ORDEN 
2020-09-21 00:53:23,509 27002 ERROR XXXX odoo.addons.meli_oerp.models.orders: insert or update on table "mercadolibre_order_items" violates foreign key constraint "mercadolibre_order_items_product_id_fkey"
DETAIL:  Key (product_id)=(1552) is not present in table "product_product".
 
Traceback (most recent call last):
  File "/opt/odoo/meli_oerp/models/orders.py", line 868, in orders_query_iterate
    self.orders_update_order_json( pdata )
  File "/opt/odoo/meli_oerp/models/orders.py", line 676, in orders_update_order_json
    order_item_ids = order_items_obj.create( ( order_item_fields ))
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3588, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3688, in _create
    cr.execute(query, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: insert or update on table "mercadolibre_order_items" violates foreign key constraint "mercadolibre_order_items_product_id_fkey"
DETAIL:  Key (product_id)=(1552) is not present in table "product_product".

2020-09-21 00:53:23,509 27002 INFO XXXX odoo.addons.meli_oerp.models.orders: orders_update_order_json > data False json:4049651410 
2020-09-21 00:53:23,510 27002 ERROR XXXX odoo.sql_db: bad query: SELECT MAX(CASE WHEN perm_read THEN 1 ELSE 0 END)
                              FROM ir_model_access a
                              JOIN ir_model m ON (m.id = a.model_id)
                              JOIN res_groups_users_rel gu ON (gu.gid = a.group_id)
                             WHERE m.model = 'mercadolibre.orders'
                               AND gu.uid = 2
                               AND a.active IS TRUE
ERROR: current transaction is aborted, commands ignored until end of transaction block

**Comment by FedericoLaTorre** [comment]
Encontré que uno de los productos del carrito tenía 3 variantes, de las cuáles el módulo solo trae 2, y la compra fue por esa tercer variante. Hasta ahora no encontré otro producto con ese problema, pero tratando de importar y actualizar varias veces los productos, esa variante nunca la trae.

**Comment by FedericoLaTorre** [comment]
Se solucionó con los últimos commits.
