### ISSUE TITLE
[12.0] No importa productos nuevos

### ISSUE THREAD

**Issue by FedericoLaTorre** [ctmil/meli_oerp#61]
No importa productos nuevos,  en el log al importar productos lista todos los números de los productos ya importados, pero no aparecen los nuevos. Tampoco aparece algún error. El producto en cuestión es el MLA904789535 y ese número nunca aparece en el log. Pero la publicación está activa y funcionando.

**Comment by FedericoLaTorre** [comment]
En la última versión importa correctamente algunos productos, pero algunos productos tira la sig. falla:

: ('El registro no existe o ha sido eliminado.\n\n(Registros: product.product(23                                                                                                                                                             05,), Usuario: 2)', None)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 2306

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1065, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('product.product(2306,).active', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/meli_oerp/models/company.py", line 525, in product_meli_get_pr                                                                                                                                                             oducts
    productcreated.product_meli_get_product()
  File "/opt/odoo/meli_oerp/models/product.py", line 1387, in product_meli_get_p                                                                                                                                                             roduct
    self._get_non_variant_attributes(rjson['attributes'])
  File "/opt/odoo/meli_oerp/models/product.py", line 757, in _get_non_variant_at                                                                                                                                                             tributes
    product_template = product.product_tmpl_id
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1065, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1053, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1096, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2835, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5167, in __getitem_                                                                                                                                                             _
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1065, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1053, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1096, in getter
    raise exception
odoo.exceptions.MissingError: ('El registro no existe o ha sido eliminado.\n\n(R                                                                                                                                                             egistros: product.product(2305,), Usuario: 2)', None)

Se probó duplicar en ML la publicación y borrar la original, pero sigue apareciendo el mismo error.

**Comment by fabriciocosta** [comment]
Este error lo cierro porque me temo que tenia que ver problemas de permisos de multicia. En todo caso los productos nuevos ahora con los ajustes al meli_util.py sobre el sdk3 de meli, no lo he visto nuevamente. Gracias
