### ISSUE TITLE
[11.0] Falla al actualizar ordenes "object has no attribute 'date_invoice'"

### ISSUE THREAD

**Issue by trixocom** [ctmil/meli_oerp#65]
2021-02-19 16:21:33,268 317 INFO base1 odoo.addons.meli_oerp.models.orders: orders_query_iterate > Error actualizando ORDEN
2021-02-19 16:21:33,269 317 ERROR base1 odoo.addons.meli_oerp.models.orders: 'dict' object has no attribute 'date_invoice'

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f0dcaa65080>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/custom/varios/meli_oerp/models/orders.py", line 1085, in orders_query_iterate
    self.orders_update_order_json( pdata )
  File "/odoo/custom/varios/meli_oerp/models/orders.py", line 987, in orders_update_order_json
    shipment = shipment_obj.fetch( order )
  File "/odoo/custom/varios/meli_oerp/models/shipment.py", line 720, in fetch
    saleorderline_item_ids.write( ( saleorderline_item_fields ) )
  File "/odoo/odoo-server/addons/sale_stock/models/sale_order.py", line 108, in write
    res = super(SaleOrderLine, self).write(values)
  File "/odoo/custom/argentina-sale/l10n_ar_sale/models/sale_order_line.py", line 146, in write
    res = super(SaleOrderLine, self).write(vals)
  File "/odoo/odoo-server/addons/sale/models/sale.py", line 898, in write
    result = super(SaleOrderLine, self).write(values)
  File "/odoo/odoo-server/odoo/models.py", line 3092, in write
    self._write(old_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3320, in _write
    self.recompute()
  File "/odoo/odoo-server/odoo/models.py", line 4907, in recompute
    vals = {n: rec[n] for n in ns}
  File "/odoo/odoo-server/odoo/models.py", line 4907, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/odoo/odoo-server/odoo/models.py", line 4761, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1028, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/odoo/custom/sale/sale_ux/models/sale_order.py", line 58, in _amount_all
    rec.env.context.date_invoice = date_order
AttributeError: 'dict' object has no attribute 'date_invoice'

**Comment by fabriciocosta** [comment]
File "/odoo/custom/sale/sale_ux/models/sale_order.py", line 58, in _amount_all
rec.env.context.date_invoice = date_order
AttributeError: 'dict' object has no attribute 'date_invoice'

sale_ux no es un addon oficial ni relacionado con meli_oerp
