### ISSUE TITLE
[14.0] Error al importar productos

### ISSUE THREAD

**Issue by FedericoLaTorre** [ctmil/meli_oerp#74]
Importó bien 134 productos y desde ahí tira este error (es una DB nueva):

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/opt/odoo/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f81a9738670>, 2, False, 'uom.uom', 'read', True, ('es_AR',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/sources/meli_oerp/models/company.py", line 527, in product_meli_get_products
    productcreated.product_meli_get_product()
  File "/opt/odoo/sources/meli_oerp/models/product.py", line 1337, in product_meli_get_product
    variant.set_bom()
  File "/opt/odoo/sources/meli_oerp/models/product.py", line 1454, in set_bom
    product_uom_id = uomobj.search([('name','=','Unidad(es)')])
  File "/opt/odoo/odoo/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo/odoo/models.py", line 4485, in _search
    model.check_access_rights('read')
  File "/opt/odoo/odoo/odoo/models.py", line 3331, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-34>", line 2, in check
  File "/opt/odoo/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_model.py", line 1742, in check
    self._cr.execute("""SELECT MAX(CASE WHEN perm_{mode} THEN 1 ELSE 0 END)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

**Comment by FedericoLaTorre** [comment]
Se solucionó con un query a la DB:

ALTER TABLE product_product DROP CONSTRAINT product_product_default_code_uniq;

Fue un módulo que probé y luego desinstalé y no eliminó el sql constrait.

**Comment by FedericoLaTorre** [comment]
En realidad el problema se presenta, primero por ese constrait, pero aparte porque define como código de producto muchas veces o la categoría o una variante, pero no para todos los productos por igual, la gran mayoría queda en blanco, que es lo que a mi entender debería pasar con todos los productos.

**Comment by fabriciocosta** [comment]
Si Federico, el tema en el modulo base de meli_oerp es crear un constraint responsivo sin romper las bases ya existentes. En la extension de Stock estamos poniendo toda la inteligencia de tratamiento por mapeo de SKU sobre las referencias internas.
Voy a cerrar este issue y agregar otro titulo como enhancement sobre un parametro de indefinicion de referencia / importacion de SKU/BARCODES que es lo que ya esta en proceso de desarrollo en el modulo base.

Gracias
