### ISSUE TITLE
[14.0] Log error al crear partner

### ISSUE THREAD

**Issue by FedericoLaTorre** [ctmil/meli_oerp#77]
Si bien sale en el log, el contacto lo crea bien, y la comprobación de VAT está apagada en la configuración. El módulo base_vat se instala sólo al instalar el plan de cuentas.

The VAT number [12345678] for partner [xxxx] does not seem to be valid.
Note: the expected format is AR200-5536168-2 or 20055361682
Traceback (most recent call last):
  File "/opt/odoo/sources/meli_oerp/models/shipment.py", line 460, in partner_delivery_id
    deliv_id = respartner_obj.create(pdelivery_fields)
  File "<decorator-gen-212>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/addons/base_vat/models/res_partner.py", line 546, in create
    return super(ResPartner, self).create(vals_list)
  File "<decorator-gen-171>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/account/models/partner.py", line 493, in create
    return super().create(vals_list)
  File "<decorator-gen-94>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_partner.py", line 568, in create
    partner._fields_sync(vals)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_partner.py", line 462, in _fields_sync
    self._commercial_sync_from_company()
  File "/opt/odoo/odoo/odoo/addons/base/models/res_partner.py", line 442, in _commercial_sync_from_company
    self.write(sync_vals)
  File "/opt/odoo/odoo/addons/base_vat/models/res_partner.py", line 552, in write
    return super(ResPartner, self).write(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_partner.py", line 546, in write
    result = result and super(Partner, self).write(vals)
  File "/opt/odoo/odoo/addons/mail/models/mail_activity.py", line 766, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 322, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/odoo/addons/website/models/mixins.py", line 182, in write
    return super(WebsitePublishedMixin, self).write(values)
  File "/opt/odoo/odoo/odoo/models.py", line 3685, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/opt/odoo/odoo/odoo/models.py", line 1260, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/l10n_ar/models/res_partner.py", line 69, in check_vat
    return super(ResPartner, self - l10n_ar_partners).check_vat()
  File "/opt/odoo/odoo/addons/l10n_latam_base/models/res_partner.py", line 22, in check_vat
    return super(ResPartner, with_vat).check_vat()
  File "/opt/odoo/odoo/addons/base_vat/models/res_partner.py", line 179, in check_vat
    raise ValidationError(msg)
odoo.exceptions.ValidationError:
The VAT number [12345678] for partner [xxxx] does not seem to be valid.
Note: the expected format is AR200-5536168-2 or 20055361682

**Comment by fabriciocosta** [comment]
Este tema de las localizaciones y los formatos lo vemos en otras localizaciones. Esto lo marco como un enhancement, y pienso que podria resolverse a nivel configuracion con un campo para el formato del VAT. Espero sugerencias.

**Comment by FedericoLaTorre** [comment]
Solo lo probé con la localización de moldeo, en principio lo resolví quitando el constrait de ls DB, pero da lugar a que a mano se anote cualquier cosa y después falle al momento de facturar.
